### PR TITLE
[FIX] connector_magento: register components only once in savepoint case

### PR DESCRIPTION
**Pull request by benrazanskas**
**[FIX] connector_magento: register components only once in savepoint case**
```
 ERROR: test_import_images_403 (odoo.addons.connector_magento.tests.test_import_product_image.TestImportProductImage)
 ` Import a product when an image respond a 403 error, should fail
 Traceback (most recent call last):
 `   File "/home/odoo/connector-magento/connector_magento/tests/test_import_product_image.py", line 91, in setUp
 `     self._build_components(StubProductAdapter,
 `   File "/home/odoo/connector/component/tests/common.py", line 204, in _build_components
 `     cls._build_component(self.comp_registry)
 `   File "/home/odoo/connector/component/core.py", line 828, in _build_component
 `     raise TypeError('Component %r (in class %r) already exists. '
 ` TypeError: Component 'stub.product.adapter' (in class <class 'odoo.addons.connector_magento.tests.test_import_product_image.TestImportProductImage.setUp.<locals>.StubProductAdapter'>) already exists. Consider using _inherit instead of _name or using a different _name.
```

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]
Perfect. As this is already included in the upstream PR https://github.com/OCA/connector-magento/pull/314 and green there, I think we can merge this once we have had another set of eyes checking this and then we can add a PR to the buildout with the bumped commit of this PR's target branch.

**Comment by benrazanskas** [comment]
> Perfect. As this is already included in the upstream PR [OCA#314](https://github.com/OCA/connector-magento/pull/314) and green there, I think we can merge this once we have had another set of eyes checking this and then we can add a PR to the buildout with the bumped commit of this PR's target branch.

Perfect, will move from current sprint to technical improvements board with state in review I guess.

**Review by MPishpecki — APPROVED** [review]

**Comment by pankk** [comment]
It seems the PR adding it to buildout isn't made yet, so I'll make it.

**Comment by pankk** [comment]
On the second thought, yes, let's do what Stefan proposed.

**Review by pankk — APPROVED** [review]

**Pull request merged**
